### ISSUE TITLE
Cannot use GPUs for training acceleration

### ISSUE THREAD

**Issue by Josh00-Lu** [Fang-Lin93/DAC#1]
Congratulations to your work. I encounter an issue with zero GPU utilities all the time. I tried the command with:
```shell
python main.py --env walker2d-medium-v2 --agent dac --eta 1 --eta_lr 0.001 --bc_threshold 1 --rho 1 --q_tar lcb --num_seed 8 --gpu 0
```
Any suggestions? Thanks

**Comment by Fang-Lin93** [comment]
Hi, thank you for your response. Have you verified if the JAX version is compatible with your CUDA version?  Updating the JAX with the command `pip install --upgrade "jax[cuda12]"` usually solves the problem. Please note that the CUDA version required for PyTorch may be different from that for JAX, which may cause compatibility issues with your installed version of PyTorch (if you have).
